apt-get update
apt-get upgrade
apt-get install \
gitk  \
toilet  \
vim  \
vlc \
unrar  \
p7zip-full  \
tmux \
g++ \
automake \
libssl-dev  \
openssh-server \
make \
clementine \
exuberant-ctags  \
tidy \
firefox \
ufraw \
firefox \
xsltproc \
maven2 \
openjdk-7-jdk  \
openjdk-7-jre \
smartmontools  \
libmozjs185-dev  \
libicu-dev  \
libcurl4-gnutls-dev  \
libtool \
erlang-dev  \
erlang-manpages  \
erlang-base-hipe  \
erlang-eunit  \
erlang-nox  \
erlang-xmerl  \
erlang-inets \
help2man zlib1g-dev rake texinfo flex dctrl-tools libsctp-dev libxslt1-dev libcap2-bin ed \
gimp \
apache2-utils \
gnuplot \
